[colors]
[colors.primary]
background = "0x242424"
foreground = "0xffffff"

[colors.normal]
black = "0x1e1e1e"
red = "0xff7b63"
green = "0x8ff0a4"
yellow = "0xf8e45c"
blue = "0x78aeed"
magenta = "0xdc8add"
cyan = "0x99c1f1"
white = "0xffffff"

[colors.bright]
black = "0x1e1e1e"
red = "0xff7b63"
green = "0x8ff0a4"
yellow = "0xf8e45c"
blue = "0x78aeed"
magenta = "0xdc8add"
cyan = "0x99c1f1"
white = "0xffffff"
