#!/bin/bash
#
# Configures the system for first-run mode, allowing certain commands
# to be run with sudo without a password.

# Exit immediately if a command exits with a non-zero status.
set -euo pipefail

#######################################
# Creates the first-run mode marker file.
#######################################
create_marker() {
  local -r marker_dir="${HOME}/.local/state/hypr"
  mkdir -p "${marker_dir}"
  touch "${marker_dir}/first-run.mode"
}

#######################################
# Sets up sudoers rules for passwordless access to specific commands.
#######################################
setup_sudoless_access() {
  local -r sudoers_file="/etc/sudoers.d/first-run"
  # Using a temporary file to avoid issues with tee and permissions.
  local temp_file
  temp_file=$(mktemp)

  cat >"${temp_file}" <<EOF
# This file is automatically generated by the hyprland installer.
# It allows passwordless sudo access for specific commands during the
# first run of the system. It is removed automatically after use.
Cmnd_Alias FIRST_RUN_CLEANUP = /bin/rm -f ${sudoers_file}
${USER} ALL=(ALL) NOPASSWD: /usr/bin/ufw
${USER} ALL=(ALL) NOPASSWD: /usr/bin/ufw-docker
${USER} ALL=(ALL) NOPASSWD: FIRST_RUN_CLEANUP
EOF

  # Atomically move the file into place with correct permissions
  sudo chown root:root "${temp_file}"
  sudo chmod 440 "${temp_file}"
  sudo mv "${temp_file}" "${sudoers_file}"
}

#######################################
# Main function
#######################################
main() {
  create_marker
  setup_sudoless_access
}

main "$@"
