# Alacritty color scheme for the Cyan Cyberpunk v2 theme

[colors]
# Default colors
primary.background = '#0a1414'
primary.foreground = '#00ffff'

# Cursor colors
cursor.text = '#0a1414'
cursor.cursor = '#00e5e5'

# Selection colors
selection.text = '#0a1414'
selection.background = '#33cccc'

# Normal colors
normal.black = '#1a2828'
normal.red = '#ff4081'
normal.green = '#2e8b57'
normal.yellow = '#adff2f'
normal.blue = '#00bfff'
normal.magenta = '#9400d3'
normal.cyan = '#00ffff'
normal.white = '#e0ffff'

# Bright colors
bright.black = '#5f9ea0'
bright.red = '#ff4081'
bright.green = '#2e8b57'
bright.yellow = '#adff2f'
bright.blue = '#00bfff'
bright.magenta = '#9400d3'
bright.cyan = '#00ffff'
bright.white = '#ffffff'