[colors]
[colors.primary]
background = '#0a0f14'
foreground = '#e6e6e6'

# Normal colors
[colors.normal]
black = '#0a0f14'
red = '#a50f15'
green = '#66a61e'
yellow = '#fec44f'
blue = '#2c5282'
magenta = '#d95f02'
cyan = '#00ffff'
white = '#e6e6e6'

# Bright colors
[colors.bright]
black = '#4a4a4a'
red = '#a50f15'
green = '#66a61e'
yellow = '#fec44f'
blue = '#2c5282'
magenta = '#d95f02'
cyan = '#00ffff'
white = '#e6e6e6'

[colors.selection]
background = '#2c5282'
foreground = '#e6e6e6'
