[colors]
[colors.primary]
background = '#0a1a3a'
foreground = '#f0f0f0'

# Normal colors
[colors.normal]
black = '#0a1a3a'
red = '#f04a4a'
green = '#1a3a1a'
yellow = '#f0c04a'
blue = '#1a3a7a'
magenta = '#f04a4a'
cyan = '#4af0f0'
white = '#f0f0f0'

# Bright colors
[colors.bright]
black = '#4a4a4a'
red = '#f04a4a'
green = '#1a3a1a'
yellow = '#f0c04a'
blue = '#1a3a7a'
magenta = '#f04a4a'
cyan = '#4af0f0'
white = '#f0f0f0'

[colors.selection]
background = '#1a3a7a'
foreground = '#f0f0f0'
