[colors]
[colors.primary]
background = '#2a2a2a'
foreground = '#f0f0f0'

# Normal colors
[colors.normal]
black = '#2a2a2a'
red = '#f04a4a'
green = '#1a3a1a'
yellow = '#f0c04a'
blue = '#5a3a1a'
magenta = '#f04a4a'
cyan = '#4af0f0'
white = '#f0f0f0'

# Bright colors
[colors.bright]
black = '#5a5a5a'
red = '#f04a4a'
green = '#1a3a1a'
yellow = '#f0c04a'
blue = '#5a3a1a'
magenta = '#f04a4a'
cyan = '#4af0f0'
white = '#f0f0f0'

[colors.selection]
background = '#5a5a5a'
foreground = '#f0f0f0'
