[colors]
[colors.primary]
background = '#004170'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#004170'
red = '#F56565'
green = '#2d4e00'
yellow = '#F6AD55'
blue = '#32668c'
magenta = '#32668c'
cyan = '#32668c'
white = '#ffffff'

# Bright colors
[colors.bright]
black = '#ced4d8'
red = '#F56565'
green = '#2d4e00'
yellow = '#F6AD55'
blue = '#32668c'
magenta = '#32668c'
cyan = '#32668c'
white = '#ffffff'

[colors.selection]
background = '#32668c'
foreground = '#ffffff'
