[colors]
[colors.primary]
background = '#2a2a2a'
foreground = '#f0f0f0'

# Normal colors
[colors.normal]
black = '#2a2a2a'
red = '#f5b7b1'
green = '#a3e4d7'
yellow = '#f9e79f'
blue = '#a9cce3'
magenta = '#d7bde2'
cyan = '#a2d9ce'
white = '#f0f0f0'

# Bright colors
[colors.bright]
black = '#888888'
red = '#f5b7b1'
green = '#a3e4d7'
yellow = '#f9e79f'
blue = '#a9cce3'
magenta = '#d7bde2'
cyan = '#a2d9ce'
white = '#f0f0f0'

[colors.selection]
background = '#888888'
foreground = '#f0f0f0'
