[colors.primary]
background = "0x212121"
foreground = "0xffffff"

[colors.normal]
black = "0x424242"
red = "0xff4081"
green = "0x4caf50"
yellow = "0xffeb3b"
blue = "0x2196f3"
magenta = "0xe91e63"
cyan = "0x00bcd4"
white = "0xffffff"

[colors.bright]
black = "0x424242"
red = "0xff4081"
green = "0x4caf50"
yellow = "0xffeb3b"
blue = "0x2196f3"
magenta = "0xe91e63"
cyan = "0x00bcd4"
white = "0xffffff"
